name: Compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 12 * * 1-5"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install SDL2 for Linux compiltion
      run: sudo apt-get install libsdl2-dev

    - name: configure for Linux compilation
      run: CFLAGS="-O2 -Wall -Wextra -I/home/runner/work/chtracker/chtracker/src/headers -Werror -I/usr/include/SDL2 -D_REENTRANT" LIBS="-L/usr/lib/x86_64-linux-gnu -lSDL2-2.0" ./configure.sh --disable-sdl
    - name: make a Linux executable
      run: make
    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: linux-executable
        path: ./chtracker

  windows:
    runs-on: ubuntu-latest
    needs: linux
    steps:
      - uses: actions/checkout@v4
      - name: Install MinGW-w64
        run: sudo apt-get install mingw-w64

      - name: build SDL2
        run: |
          git clone -b SDL2 https://github.com/libsdl-org/SDL.git
          mkdir libsdl
          mkdir SDL/build
          cd SDL/build
          ../configure --host=x86_64-w64-mingw32 --prefix=$PWD/../../libsdl --disable-shared --enable-static
          make
          make install
          cd ../..

      - name: configure for Windows cross-compilation
        run: CFLAGS="-O2 -I$PWD/libsdl/include/ -Dmain=SDL_main -I$PWD/src/headers -Wall -Wextra -Werror" LIBS="$(./libsdl/bin/sdl2-config --libs) --static" CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ ./configure.sh --disable-sdl
      - name: make a Windows executable
        run: make
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: ./chtracker.exe
