name: compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 12 * * 1-5"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup SDL
      uses: libsdl-org/setup-sdl@v1

    - name: configure
      run: ./configure.sh
    - name: make
      run: make
